# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XTTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XTTemplate
  pod 'DZNEmptyDataSet'
  
  pod 'Aspects'
  
  pod 'ReactiveObjC'
  
  pod 'YTKNetwork'
  
  pod 'lottie-ios'

  target 'XTTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XTTemplateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
